### ISSUE TITLE
Update description of official game source code.

### ISSUE THREAD

**Issue by notkaif** [FunkinCrew/awesome-funkin-resources#196]
Under the programming section where it has a hyperlink to the official games source code, it states that it was last updated for Week 7. This is no longer true as the full Weekend 1, aka v0.3 source code has been migrated into the repository.

<img width="647" alt="image" src="https://github.com/FunkinCrew/awesome-funkin-resources/assets/62565537/88b6c25a-08cb-48a4-9d47-3c8c86fc04d3">

**Comment by NotHyper-474** [comment]
Fixed by #197

**Comment by EliteMasterEric** [comment]
Solved.
